### ISSUE TITLE
Unable to build with rust 1.40.0

### ISSUE THREAD

**Issue by yaa110** [SergioBenitez/cookie-rs#136]
```rust
error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.13.1/src/lib.rs:806:47
    |
806 |           static MAX_DATETIME: OffsetDateTime = date!(9999-12-31)
    |  _______________________________________________^
807 | |             .with_time(time!(23:59:59.999_999))
808 | |             .using_offset(offset!(UTC));
    | |_______________________________________^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0015`.
error: could not compile `cookie`.
```

```
rustc --version
rustc 1.40.0 (73528e339 2019-12-16)
```

**Comment by SergioBenitez** [comment]
This is a semver breakage in `time`. The method `using_offset` in `time` 0.2.4 was `const` while it is _not_ `const` in 0.2.5. This should be fixed in `time`, or if it cannot, we can declare `MAX_DATETIME` as a local.

**Comment by yaa110** [comment]
Please use `time = "=0.2.4"` in `Cargo.toml` to fix it

**Comment by SergioBenitez** [comment]
Was already on it. Released as `0.13.2`.
